### PR TITLE
Browser installations

### PR DESCRIPTION
**Pull request by inikulin**
/cc @kirovboris @AlexanderMoskovkin

### CODE REVIEW

**Comment by kirovboris** [comment]
LGTM

**Comment by kirovboris** [comment]
Tests don't pass. Fix it.

**Comment by inikulin** [comment]
FPR

**Comment by kirovboris** [comment]
LGTM

**Comment by inikulin** [comment]
FPR

**Comment by kirovboris** [comment]
LGTM

**Comment by AlexanderMoskovkin** [comment]
LGTM

**Comment by inikulin** [comment]
Thanks

**Pull request merged**
