### PR TITLE
Message formatters

### PR DESCRIPTION
**Pull request by kirovboris**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
Hm, it's quite far from what we've discussed. Can you explain how it works, who it should be used and what separate entities mean (especially I don't get what `base` and `plain-text` means now.

**Comment by kirovboris** [comment]
Base formatter provides capability format error message in base format use tags.
Like: `some code...` -> `<related-code>some code</related-code>`
Plain text formatter converts base format to plain text.
```javascript
var baseErrMsg = "some message" + baseFormatter.wrapLink("http://some_link") + "...";

//format "some message<link>http://some-link</link>" to target format, 
//in this case to plain text
var formattedMsg = formatPlainText(baseErrMsg);
...
```
What needs restructure? What a way to use expected?

**Comment by inikulin** [comment]
Emm,

```js
var formatter = new PlainTextFormatter();

var msg = formatter.getErrorText(err);
```

**Comment by kirovboris** [comment]
Ok, I'll fix it. base.js is just base class, I thought we discussed use Decorator template for this functionality.

**Comment by inikulin** [comment]
Let's discuss it in person in office tomorrow at first. I thought, and decided that I don't like my approach either. We need a brainstorm.

**Comment by kirovboris** [comment]
Ok

**Pull request closed without merging**
