### PR TITLE
Browser connection tests

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @churkin 
@VasilyStrelyaev please check the spelling in strings

**Warning:** I've temporary added `node_modules/hammerhead` for the testing purposes. So, review just the first commit. Second contains huge diff with the hammerhead's code and deps

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@inikulin The Travis CI build failed

**Comment by inikulin** [comment]
FPR

**Comment by churkin** [comment]
LGTM

**Comment by AlexanderMoskovkin** [comment]
LGTM

**Comment by VasilyStrelyaev** [comment]
Test names:
Should fire "ready" event once established and redirect to idle page -> Should fire "ready" event and redirect to idle page once established
Should respond with error on queries if not ready -> Should respond to queries with error if not ready

**Comment by inikulin** [comment]
FPR

**Comment by VasilyStrelyaev** [comment]
LGTM

**Comment by inikulin** [comment]
Thanks

**Pull request merged**
