### PR TITLE
Runner.browser() now accepts browser path (fixes #128)

### LINKED ISSUE #128: We should disable coloring in CLI if stdout is not a TTY

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @AndreyBelym

### CODE REVIEW

**Comment by AndreyBelym** [comment]
You need to rename _convertBrowserAliasToBrowserInfo to_convertAliasOrPathToBrowserInfo in tests: https://github.com/superroma/testcafe-phoenix/blob/master/test/server/runner-test.js#L469

**Comment by AndreyBelym** [comment]
Can you also change mock browser names in https://github.com/superroma/testcafe-phoenix/blob/master/test/server/runner-test.js#L520 and https://github.com/superroma/testcafe-phoenix/blob/master/test/server/runner-test.js#L542, please?

**Comment by inikulin** [comment]
FPR

**Comment by inikulin** [comment]
FPR added test corrections suggested by @AndreyBelym

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by AndreyBelym** [comment]
lgtm

**Pull request merged**
