### PR TITLE
Switch to the NPM version of the hammerhead (closes #44, closes #47, closes #70)

### LINKED ISSUE #44: Switch to the NPM version of the hammerhead
Requires superroma/testcafe-hammerhead#25 resolution

### LINKED ISSUE #47: Get rid of 'jobOwnerToken' and 'jobUid' in the code
As a continuation of the superroma/testcafe-hammerhead#65 we need to remove `jobUid` and `jobOwnerToken` from the client code and replace it with the `sessionId`. We need to do that for the tests and server (if we have anything there) as well.

### LINKED ISSUE #70: Client-side refactoring: use `hammerhead` instead of `hammerheadAPI`

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
The PR contains two commits:

1) Removing all from the `node_modules` (`hammerhead` and `_compiled_` dirs);
2) Switch to the `npm` version of `testcafe-hammerhead` (`package.json` update, switch to the new api, some fixes, get rid of [a hammerhead related qunit test](https://github.com/superroma/testcafe-hammerhead/pull/143))

/cc @inikulin @helen-dikareva @AndreyBelym

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by helen-dikareva** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by AlexanderMoskovkin** [comment]
tests are ok now

**Comment by helen-dikareva** [comment]
lgtm

**Comment by AndreyBelym** [comment]
lgtm

вт, 6 окт. 2015, 13:13, helen-dikareva <notifications@github.com>:

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
thanks

**Pull request merged**
