### PR TITLE
QUnit CI implemented, node stable test configuration added (closes #5…

### LINKED ISSUE #65: Add node v4 test configuration

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
…3, closes #65)

- Saucelabs settings added
- Some qunit tests was fixed (they were failed in Chrome on saucelabs)
- One qunit test was removed because of the [testcafe-hammerhead issue](https://github.com/superroma/testcafe-hammerhead/issues/171)

testcafe-build-bot was setup for this repo, so the bot should run the tests now

/cc @inikulin @helen-dikareva

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
hmm, something was wrong with testcafe-build-bot here. I'll play with this PR. When it will work I write a comment

**Comment by AlexanderMoskovkin** [comment]
FPR

**Comment by helen-dikareva** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
