### PR TITLE
Small refactoring

### PR DESCRIPTION
**Pull request by churkin**
\cc @inikulin 

I think it is more logical.

### CODE REVIEW

**Comment by inikulin** [comment]
Tests fail due to incorrect ES6 syntax

**Comment by inikulin** [comment]
Moreover more likely `es7.classProperties` will not make it (see: https://github.com/babel/babel/issues/1990), so there will be a task to remove them completely from the codebase.

**Comment by inikulin** [comment]
Issued a bug: https://github.com/superroma/testcafe-phoenix/issues/37. @churkin Can you do the same for the hammerhead?

**Comment by churkin** [comment]
Of course

**Comment by inikulin** [comment]
I think since it's constants anyway we will replace it with the instance vars, e.g.:
`static TIMEOUT = 123;` -> `this.TIMEOUT = 123;`. It's also will simplify some tests, since we will not need to restore constant var value.

**Comment by churkin** [comment]
In this case "var instanceCount = 0;" is a real static field :)

**Comment by inikulin** [comment]
Yes, this case is an exception. But currently we've used static fields only for the constants which can be modified for testing purposes.

**Pull request closed without merging**
