### PR TITLE
Don't allow es6-promise pollute `window` in client scripts (close #78)

### LINKED ISSUE #78: Don't allow es6-promise pollute `window` in client scripts
see: https://github.com/superroma/testcafe-hammerhead/blob/master/Gulpfile.js#L135

### PR DESCRIPTION
**Pull request by helen-dikareva**
Fix is the same like in hammerhead
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
@inikulin As I see, the pr description contains the `close #` directive, but the commit name doesn't. It works correctly, the issue will be closed when the pr merged. But should we always add the `close #` directive to commits descriptions or is the directive in a pr title enough?

**Comment by inikulin** [comment]
@AlexanderMoskovkin I'd rather keep both. But if you are asking it context of the bot "release" functionality, I'd stick with the PR's directive since it's may contain multiple commits.

**Comment by inikulin** [comment]
So the rule is: always use both

**Comment by AlexanderMoskovkin** [comment]
ok
so, @helen-dikareva , please add the `close` directive to the commit name

/r-

**Comment by helen-dikareva** [comment]
Rename is done. Please merge.

**Comment by inikulin** [comment]
lgtm

**Pull request merged**
