### PR TITLE
Fix broken word wrapping in reporters in Windows TTY (closes #87)

### LINKED ISSUE #86: `xunit` and `json` reporters should always use plain-text decorator

### LINKED ISSUE #87: Word wrapping is broken in reporters in Windows TTY

### PR DESCRIPTION
**Pull request by kirovboris**
\cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
Have you tried it in MacOS TTY, is everything works as expected there?

**Comment by kirovboris** [comment]
FPR
Yes the output to MacOS TTY works as expected, I renamed the commit.

**Comment by inikulin** [comment]
Please, use `Fix` word in the commit message, because currently it sounds like you've introduced the issue with the commit :smile:

**Comment by kirovboris** [comment]
Okay

**Comment by inikulin** [comment]
lgtm

**Comment by inikulin** [comment]
\cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
