### PR TITLE
New task completion and abortion mechanism (fixes #33).

### LINKED ISSUE #33: Browser job completion mechanism is incorrect.
There are two ways which leads to the job completion:

1. All job's test runs are finished.
2. Job's task was aborted 

In the first scenario browser requests status an we query job in the front of the queue for the next test run. If job doesn't contain pending test runs any more it returns `null` and raises `done` event. `done` event handler in the `BrowserConnection` removes job from the queue. But since `BrowserConnection.getStatus()` already queried queue browser goes to the `idle` state. It will query status anyway, however it leads to the unecessary delay.

The second scenario has more complicated problems. Task calls `abort()` for each of it's jobs. `abort()` just cleans pending test runs queue. So, from the browsers perspective we will have the same issue as described for the first case. The other issue for this approach is that we still relay on `done` event for the abortion scenario which is really fragile. `done` event on all jobs will trigger `done` event for the task. Which is wrong. Currently we rely on the fact that adopting code will call `task.removeAllListeners()` immediately after `task.abort()` which is definetly uncool.

The proposal is:
* Do not rely on the `done` event of the job in the `BrowserConnection`. Use the following algorithm instead: 
  1. If `jobQueue` is empty then switch browser to the `idle` state and abort these steps.
  2. Try query job in the front of the queue. If it returns `null` then shift the queue and repeat this step. Else pass returned test run to the browser.
   
* `task.abort()` should immediately remove all task's jobs from the appropriate browser connections.

### PR DESCRIPTION
**Pull request by inikulin**
In general it's the implementation of the last proposal in the #33 with some simplification.

### CODE REVIEW

**Comment by inikulin** [comment]
\cc @kirovboris @AlexanderMoskovkin @churkin

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
@kirovboris ping

**Comment by kirovboris** [comment]
lgtm

**Pull request merged**
