### PR TITLE
Stop requests to the server before redirect from the idle-page

### PR DESCRIPTION
**Pull request by AlexanderMoskovkin**
After the #66 issue was closed I've found a problem on the idle-page script. I've fixed it here

/cc @inikulin @helen-dikareva

### CODE REVIEW

**Comment by helen-dikareva** [comment]
lgtm

**Comment by inikulin** [comment]
lgtm

**Comment by inikulin** [comment]
@AlexanderMoskovkin Too late, but I've just had a thought what the following condition will be more clear:
```js
function checkStatus (statusUrl) {
    browser
        .checkStatus(statusUrl, window.XMLHttpRequest)
        .then((cmd) => {
            if (cmd !== COMMAND.idle)
                window.clearInterval(interval);
        });
}
``` 

What do you think?

**Comment by AlexanderMoskovkin** [comment]
yes, it's more clear. Create a new pr?

**Comment by inikulin** [comment]
@AlexanderMoskovkin Yes, please

**Pull request merged**
