### PR TITLE
Restructure project. Move assets to the appropriate dirs. 

### PR DESCRIPTION
**Pull request by inikulin**
\cc @kirovboris @churkin @AlexanderMoskovkin

### CODE REVIEW

**Comment by inikulin** [comment]
Fixed lint errors. Please, review

**Comment by kirovboris** [comment]
Modules "callsite" and "useragent" were added, but they are nowhere used.

**Comment by inikulin** [comment]
@kirovboris 
1.  https://github.com/superroma/testcafe-phoenix/blob/master/src/utils/read-file-relative.js#L6
2.  https://github.com/superroma/testcafe-phoenix/blob/master/src/browser/connection.js#L70

**Comment by kirovboris** [comment]
ok, LGTM

**Comment by AlexanderMoskovkin** [comment]
LGTM

**Comment by churkin** [comment]
LGTM

**Comment by inikulin** [comment]
Thanks

**Pull request merged**
