### PR TITLE
Use getter for the nextTestRunUrl. Implement Runner.src() and Runner.filter(). Add temporary ugly adapter for the old fixture compiler.

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @churkin @kirovboris 
@VasilyStrelyaev please, check the strings in tests and error messages.

P.S. `src/compiler/old` contains old fixture compiler code without modification. You shouldn't review it, since it will be replaced with the new compiler later.

### CODE REVIEW

**Comment by churkin** [comment]
lgtm

**Comment by inikulin** [comment]
tests are failing.

**Comment by inikulin** [comment]
FPR

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by kirovboris** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
thx

**Pull request merged**
