### PR TITLE
Runner tests. Fix some edge cases with the browsers bootsrapping.

### PR DESCRIPTION
**Pull request by inikulin**
/cc @churkin @AlexanderMoskovkin 
@VasilyStrelyaev Please, check spelling in strings.

### CODE REVIEW

**Comment by VasilyStrelyaev** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
LGTM

**Comment by churkin** [comment]
LGTM

**Comment by inikulin** [comment]
thx

**Pull request merged**
