### PR TITLE
Switch to testcafe-browser-natives. Free local browser connections as soon as possible.

### PR DESCRIPTION
**Pull request by inikulin**
Fix minor issues in previous Reporters PR as well

\cc @AlexanderMoskovkin @churkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
@churkin Any chance it will be reviewed in the near future? )

**Comment by churkin** [comment]
lgtm

**Comment by inikulin** [comment]
Thx)

**Pull request merged**
