### PR TITLE
check expected browser dialogs only before start new step (close #140)

### LINKED ISSUE #140: We ignore browser dialogs that occur during the delay between steps
T297711

### PR DESCRIPTION
**Pull request by helen-dikareva**
Regression functional test was added in minor version. We'll move it with others functional test.
/cc @inikulin @AlexanderMoskovkin

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
@helen-dikareva please rebase to the `master` branch to fix the tests (because of https://github.com/superroma/testcafe-phoenix/issues/153)

**Comment by helen-dikareva** [comment]
Done

**Comment by inikulin** [comment]
lgtm

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Pull request merged**
