### PR TITLE
Get rid of await* (fixes #30)

### LINKED ISSUE #30: Get rid of await*
`await *` didn't make it: https://github.com/tc39/tc39-notes/blob/master/es7/2015-07/july-30.md#64-advance-async-functions-to-stage-2 :disappointed: So, most likely it will be removed in the future versions of Babel. 

Instead of
```js
await * arr;
```
use
```js
await Promise.all(arr)
```

\cc @churkin @AlexanderMoskovkin Please, check the presence of this syntax in the hammerhead and browser-natives.

@kirovboris @AndreyBelym @LavrovArtem @miherlosev @arubtsov @helen-dikareva - just FYI

### PR DESCRIPTION
**Pull request by inikulin**
\cc @AlexanderMoskovkin @kirovboris

### CODE REVIEW

**Comment by AlexanderMoskovkin** [comment]
lgtm

**Comment by inikulin** [comment]
@kirovboris ping

**Comment by kirovboris** [comment]
lgtm

**Comment by inikulin** [comment]
thx

**Pull request merged**
